import { Inter } from "next/font/google";
import "./globals.css";
import Topbar from "@/components/shared/Topbar";
import LeftSidebar from "@/components/shared/LeftSidebar";
const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Topbar />
        <main className="flex flex-row">
          {/* <main > */}
          <LeftSidebar />
          <section className="main-container">
            <div className="w-full max-w-7xl">{children}</div>
            <div className="absolute top-0 right-10"></div>
          </section>
          {/* @ts-ignore */}

          {/* <RightSidebar /> */}
        </main>
      </body>
    </html>
  );
}
