import { Inter } from "next/font/google";
import "./globals.css";
import Topbar from "@/components/shared/Topbar";
import LeftSidebar from "@/components/shared/LeftSidebar";
import Bottombar from "@/components/shared/Bottombar";
import { Navbar } from "@/components/shared/Navbar";
const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Template",
  description: "Generated by esquiz.com",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <Navbar />
        <main className="container">
          {children}

          {/* <main > */}
          {/* <LeftSidebar /> */}
          {/* <section className="main-container"> */}
          {/* <section>
            <div className="w-[100%] max-w-7xl"></div>
            <div className="absolute top-0 right-10"></div>
          </section> */}
          {/* @ts-ignore */}

          {/* <RightSidebar /> */}
          <Bottombar />
        </main>
      </body>
    </html>
  );
}
